name: js_bookstore
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  # Font
  google_fonts: ^6.1.0
  # Device_Preview
  device_preview: ^1.1.0
  # Splash
  animated_splash_screen: ^1.3.0
  # Bottom Navigation
  floating_bottom_navigation_bar: ^1.5.2
  # Bottom Sheet
  bottom_sheet: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans_Bold.ttf
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
